### ISSUE TITLE
MAP_AT_K implementation is wrong

### ISSUE THREAD

**Issue by abitbetter** [recommenders-team/recommenders#1702]
### Description

Hi, after several thoughts on it and performing my own tests, I think that the implementation of map_at_k is not correct.

[https://github.com/microsoft/recommenders/blob/main/recommenders/evaluation/python_evaluation.py](https://github.com/microsoft/recommenders/blob/main/recommenders/evaluation/python_evaluation.py)

The return statement shows the following:

`return (df_merge["rr"] / df_merge["actual"]).sum() / n_users`

Although the function documentation does advice that:

`2. The MAP is meant to calculate Avg. Precision for the relevant items, so it is normalized by the number of
        relevant items in the ground truth data, instead of k.`

I think it is mistaken and should normalize (divide) by the min(k, actual). 

By dividing just by the "actual" column, what is computed is the recall, not the precision.
In other words, if I measure how well I am recommending some items to a user, by dividing by the "actual" makes the MAP for that user dependent on how many items he/she bought.  So if I recommend 3 items and the user purchases those 3 plus 5 more, the MAP metric will be different to a situation in which I recommend 3 items and the user purchases those 3 plus 10 more.  Which doesn't make sense because the mean average precision should be independent of how many items are purchased (unless actual < k) as it is expected to measure precision, not recall.

Having said the above, I think that the return value should be instead something similar to this:
`df_merge["top_k"] = k`
 `df_merge["denominator"] = df_merge[["top_k", "actual"]].min(axis=1)`
` return (df_merge["rr"] / df_merge["denominator"]).sum() / n_users`

I would really appreciate your comments on this!

Thank you in advance!

**Comment by anargyri** [comment]
Well, we have seen different ways to define these metrics in the literature and practice. We opted to follow the Spark MLLib definition of MAP, as we note in the docstring i.e. the definition that can be found here https://spark.apache.org/docs/2.3.0/mllib-evaluation-metrics.html#ranking-systems
They divide by the "actual" number, whereas @abitbetter suggests dividing my min(k, actual) instead.
There are pros and cons for both ways; I see the argument in favor of the latter but on the other side if k is larger than the number of relevant items then it is not possible to achieve 100% precision with the latter definition.
I suggest that @abitbetter implements the alternative definition so that it can be activated with a flag (a boolean argument added in the MAP signature). Also to add a case testing this definition in the MAP test.

**Comment by anargyri** [comment]
I think it would be good to provide a reference for the proposed definition, but I think one desired feature is that MAP increases with k. The definition we use is used in information retrieval, see e.g. https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision from information retrieval where typically there are more relevant documents than k.

**Comment by yueguoguo** [comment]
The document of Spark MLlib indeed says the MAP is calculated based on the actual relevant item. However, I also found that the formula used in precision@k on the same page uses min value of actual relevant items and k. Plus, I see discussions in different places about MAP where the two are misused...

Here is my suggestion:
* I would agree on what @abitbetter suggested as MAP calculates the "mean" of average precision which essentially is precision@k so it should be consistent with the definition of precision@k. 
* Perhaps the precision@k function in the same .py file needs to be updated as well because it calculates the precision by using only `k` as the denominator - similar to above, the min value of `k` and "actual" should be used.
