### ISSUE TITLE
[BUG] Issue with SARplus in the latest merge to main issue with permissions

### ISSUE THREAD

**Issue by miguelgfierro** [recommenders-team/recommenders#2081]
### Description

The tests broke: https://github.com/recommenders-team/recommenders/actions/runs/8574327835/job/23500897002

@SimonYansenZhao it seems it is something related to permissions.

**Comment by SimonYansenZhao** [comment]
@miguelgfierro I find it is because the GPG key (`SARPLUS_GPG_PRI_KEY_ASC ` stored in [Actions Secrets](https://github.com/recommenders-team/recommenders/settings/secrets/actions)) expired.  Now the expiration date has been updated, and the tests passed: https://github.com/recommenders-team/recommenders/actions/runs/8574327835
